apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cipherchat
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml            # placeholder values — replace or manage via External Secrets
  - backend-deployment.yaml
  - backend-service.yaml
  - backend-hpa.yaml
  - frontend.yaml
  - ingress.yaml
images:
  - name: ghcr.io/simran1002/cipherchat-backend
    newTag: latest          # CI: kustomize edit set image ...:${GITHUB_SHA}
  - name: ghcr.io/simran1002/cipherchat-frontend
    newTag: latest
